export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'


export const RESET_CART = 'RESET_CART'
export const SET_PAYER_CONTACT = 'SET_PAYER_CONTACT'

export const FISCALIZE_SUCCESS = 'FISCALIZE_SUCCESS'
export const FISCALIZE_FAILURE = 'FISCALIZE_FAILURE'
export const FISCALIZE_PENDING = 'FISCALIZE_PENDING'



export const CHECKOUT_CART = 'CHECKOUT_CART'
export const CHECKOUT_UPDATE_CART = 'CHECKOUT_UPDATE_CART'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'






export const ADD_PAYMENT_TO_CART = 'ADD_PAYMENT_TO_CART'
export const REMOVE_PAYMENT_FROM_CART = 'REMOVE_PAYMENT_FROM_CART'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS'
export const SALE_SEQ_INCREMENT = 'SALE_SEQ_INCREMENT'


export const INITED = 'INITED'



export const FISCALIZE = 'FISCALIZE'
export const FETCH_DEMO_ITEMS = 'FETCH_DEMO_ITEMS'
export const FETCH_DEFAULT_PAYMENTS = 'FETCH_DEFAULT_PAYMENTS'



